pipeline {

    agent any

    tools {
        jdk 'OpenJDK 17.0.4'
        nodejs 'NodeJS 18.18.2'
    }

    
    environment {
        GITHUB_TOKEN = credentials("GITHUB_TOKEN_KB")

    }

    stages {
         
        stage("display repositories") {
            steps {

             sh "ls -alh"
            }
        }

          
        stage("build") {
            steps {
            sh "sh ./jenkins/commands.sh ${GITHUB_TOKEN} passed_message"
            sh "ls -alh"
            dir('public') {
                sh "ls -alh"
                }
            dir('public/docs') {
                sh "ls -alh"
                }
            }

        }

                 
        stage("post-build") {
            steps {
                 sh "ls -alh"

                echo 'Starting the build Stage'
            }
        }

    }

}

