pipeline {

    agent any

    tools {
        nodejs 'NodeJS 18'
    }


    environment {
        GITHUB_TOKEN = credentials("GITHUB_TOKEN")

    }

    stages {
         

        stage("Process Document") {
            steps {
            sh "sh ./jenkins/commands.sh ${GITHUB_TOKEN} java-test-repository"
            dir('reactApp/public/docs') {
                sh "ls -alh"
                }
            }
        }
        stage("Install Dependencies") {
            steps {
            echo 'Installing Dependencies'
            dir('reactApp/') {
                sh '''
                    npm install
                    npm i -g tsx
                '''
                }
            }
        }

        stage("post-build") {
            steps {
            echo 'Deploying the App'
            dir('reactApp/') {
                sh "ls -alh"
                sh 'npm run deploy'
                }
            }
        }

    }

}

